#!/usr/bin/env python3
"""
Palette smoke test — fails when a generated asset drifts off the Phase 1 palette.

The whole point of the revamp is "one palette, everywhere". Four different accent
languages is exactly the failure mode that is easy to reintroduce by hand (a
one-off badge tweak, a library default, an upstream action changing its output),
and it is invisible in a diff. So this script asserts it mechanically.

Checks
  1. Banned colours — the retired violet/emerald/navy accents must not appear in
     any build input or generated asset.
  2. Asset allow-list — every colour in a generated SVG must belong to that
     file's theme palette (hex and rgba forms).
  3. Ramp check — the reactor's week ring is a computed ramp rather than palette
     hexes, so each rgb() must lie on that theme's declared ramp stops (dark:
     cyan->gold, light: cyan->green->gold).
  4. README badge URLs — every colour query parameter must be a palette value.

Docs (`*.md` manuals, guide.md) are deliberately out of scope: they are
historical records and legitimately quote the old palette.

Exit code 0 = on palette, 1 = drift. Run: python3 scripts/check_palette.py
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---- canonical palette (mirrors stark-industries-profile-revamp.md Phase 1) ----
DARK = {
    "05060A",  # deep space background
    "030409",  # panel gradient end / frame
    "080C14",  # panel surface (projects grid, radar card)
    "0A0E16",  # title bar / panel bar
    "00E5FF",  # arc-reactor cyan — structure
    "FFC857",  # repulsor gold — emphasis
    "2ED573",  # success green — state
    "F8FAFC",  # primary text
    "8892A6",  # titanium grey — secondary
    "4E5868",  # dim tier of titanium
    "1A2230",  # empty portrait-grid cell tier
}
LIGHT = {
    "F8FAFC",  # background
    "E2E8F0",  # panel gradient end
    "F1F5F9",  # panel bar
    "FFFFFF",  # panel
    "0891B2",  # cyan (light)
    "A16207",  # gold (light)
    "059669",  # green (light)
    "0F172A",  # text
    "64748B",  # secondary
    "94A3B8",  # dim tier
    "05060A",  # window frame in light mode
}
THEME_ALLOW = {"dark": DARK, "light": LIGHT}
DIVIDER_DARK = {"00E5FF", "FFC857"}
DIVIDER_LIGHT = {"0891B2", "A16207"}
# macOS window chrome in the banner terminal — authentic, not a palette accent.
TRAFFIC_LIGHTS = {"FF5F56", "FFBD2E", "27C93F"}

# ---- retired palette. If any of these reappear, something regressed. ----
BANNED = {
    "A78BFA", "7C3AED", "22D3EE", "10B981", "0A101F", "0C1426", "0B1222",
    "EF4444", "DC2626", "EAB308", "0D1117", "1E1B4B", "DDD6FE", "6366F1",
    "818CF8", "A5B4FC", "2D3343", "475569",
}

# ---- what to scan ----
DARK_ASSETS = [
    "dark_v3.svg",
    "assets/dark_v3.svg",
    "assets/projects.svg",
    "projects/projects.svg",
    "out/projects.svg",
    "out/radar.svg",
    "assets/divider.svg",
]
LIGHT_ASSETS = [
    "light_v3.svg",
    "assets/light_v3.svg",
    "out/projects-light.svg",
    "out/radar-light.svg",
    "assets/divider-light.svg",
]
# Ramp assets: path -> (theme, stops). A stop list, not a segment: dark walks a
# straight cyan -> gold line, light routes through the palette green because
# interpolating cyan straight to gold on white collapses chroma to ~23 (a muddy
# sage) at mid-scale. Mirrors generate_reactor.py RAMPS; scripts/test_reactor.py
# asserts the two stay in sync so the gate cannot silently drift from the source.
RAMP_ASSETS = {
    "dark": ("out/reactor.svg", ((0, 229, 255), (255, 200, 87))),
    "light": ("out/reactor-light.svg", ((8, 145, 178), (5, 150, 105), (161, 98, 7))),
}
SOURCES = [
    "generate_banner.py",
    "generate_banner_v2.py",
    ".github/scripts/generate_projects.py",
    ".github/scripts/generate_radar.py",
    ".github/scripts/generate_reactor.py",
    ".github/scripts/fetch_reactor.py",
    "scripts/game-of-life/render_svg.py",
    ".github/workflows/projects.yml",
    "README.md",
]
# Generated by CI, absent on a fresh clone — skipped with a note, not a failure.
OPTIONAL_DIRS = ("out/",)

README_COLOR_PARAMS = {
    "background", "stroke", "ring", "fire", "currstreaklabel", "sidelabels",
    "currstreaknum", "sidenums", "dates", "titlecolor", "title_color",
    "icon_color", "text_color", "bg_color", "color", "quotecolor",
    "authorcolor", "symbolcolor", "backgroundcolor", "bordercolor", "qcolor",
    "acolor", "textcolor",
}

# ---- colour extraction (attribute values only: avoids &#9656; style entities) ----
COLOR_ATTR = re.compile(r'(?:fill|stroke|stop-color|flood-color|color)="([^"]+)"')
STYLE_ATTR = re.compile(r'style="([^"]+)"')
STYLE_COLOR = re.compile(r"(?:fill|stroke|stop-color)\s*:\s*([^;\"']+)")
ANIM_COLOR = re.compile(r'attributeName="(?:stop-color|fill)"\s+values="([^"]+)"')
HEX = re.compile(r"^#?([0-9A-Fa-f]{6})$")
RGBA = re.compile(r"rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*[\d.]+\s*)?\)")
RGB_ANY = re.compile(r"rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)")
# Paint keywords that are not colours, and animation fill-modes seen on <animate fill="freeze">.
SKIP = re.compile(r"^(?:none|transparent|currentcolor|inherit|context-fill|freeze|remove)$|^url\(", re.I)


def read(path):
    with open(os.path.join(ROOT, path), encoding="utf-8") as f:
        return f.read()


def colors_in(svg):
    """Yield raw colour tokens used in paint attributes (and animated stop-colors)."""
    tokens = []
    for match in COLOR_ATTR.finditer(svg):
        tokens.append(match.group(1).strip())
    for match in STYLE_ATTR.finditer(svg):
        tokens.extend(t.strip() for t in STYLE_COLOR.findall(match.group(1)))
    for match in ANIM_COLOR.finditer(svg):
        tokens.extend(t.strip() for t in match.group(1).split(";"))
    return tokens


def rgb_hex(token):
    m = RGBA.match(token)
    if not m:
        return None
    return "".join(f"{int(v):02X}" for v in m.groups())


def check_banned(path, text, failures, counts):
    for hexcode in sorted(BANNED):
        n = len(re.findall(re.escape("#" + hexcode), text, re.I))
        if n:
            failures.append(f"{path}: banned retired palette colour #{hexcode} x{n}")
    return counts


def check_asset(path, allowed, failures, report):
    svg = read(path)
    allowed = {c.upper() for c in allowed}
    seen, bad = set(), []
    for token in colors_in(svg):
        if not token or SKIP.match(token):
            continue
        if token.startswith("rgb"):
            as_hex = rgb_hex(token)
            if as_hex is None or as_hex not in allowed:
                bad.append(token)
            else:
                seen.add(as_hex)
            continue
        m = HEX.match(token)
        if m and m.group(1).upper() in allowed:
            seen.add(m.group(1).upper())
        else:
            bad.append(token)
    for token in sorted(set(bad)):
        failures.append(f"{path}: off-palette colour {token}")
    report.append(f"{path}: {len(seen)} palette colours in use")


def dist_to_segment(point, a, b):
    """Shortest distance from an RGB point to an RGB segment."""
    edge = [b[i] - a[i] for i in range(3)]
    elen = sum(e * e for e in edge)
    t = 0.0 if elen == 0 else max(0.0, min(1.0, sum((point[i] - a[i]) * edge[i] for i in range(3)) / elen))
    return sum((point[i] - (a[i] + t * edge[i])) ** 2 for i in range(3)) ** 0.5


def check_ramp(path, theme, stops, failures, report):
    svg = read(path)
    worst, count = 0.0, 0
    for m in RGB_ANY.finditer(svg):
        point = tuple(int(v) for v in m.groups())
        count += 1
        # distance from this colour to the nearest point on the ramp polyline
        worst = max(worst, min(
            dist_to_segment(point, stops[i], stops[i + 1]) for i in range(len(stops) - 1)
        ))
    if worst > 6.0:
        failures.append(f"{path}: {count} rgb() week arcs, worst drift {worst:.1f} off the cyan->gold ramp")
    else:
        report.append(f"{path}: {count} rgb() week arcs, max {worst:.1f} off the cyan->gold ramp")

    allowed = {c.upper() for c in THEME_ALLOW[theme]}
    bad = set()
    for token in colors_in(svg):
        if not token or SKIP.match(token) or token.startswith("rgb"):
            continue
        m = HEX.match(token)
        if not m or m.group(1).upper() not in allowed:
            bad.add(token)
    for token in sorted(bad):
        failures.append(f"{path}: off-palette colour {token}")


def check_readme_params(failures):
    text = read("README.md")
    allowed = {c.upper() for c in DARK | LIGHT | TRAFFIC_LIGHTS | DIVIDER_DARK | DIVIDER_LIGHT}
    found = 0
    for value in re.findall(r"[?&]([A-Za-z_]+)=([^&\s\"')]+)", text):
        param, raw = value[0], value[1]
        if param.lower() not in README_COLOR_PARAMS:
            continue
        candidate = raw.replace("%23", "").replace("#", "").upper()
        if not re.fullmatch(r"[0-9A-F]{3}|[0-9A-F]{6}", candidate):
            continue
        found += 1
        if candidate not in allowed:
            failures.append(f"README.md: badge param ?{param}={raw} is off-palette")
    return found


def main():
    failures, report = [], []

    for path in SOURCES:
        if not os.path.exists(os.path.join(ROOT, path)):
            failures.append(f"{path}: missing (expected build input)")
            continue
        check_banned(path, read(path), failures, None)

    ramp_paths = [entry[0] for entry in RAMP_ASSETS.values()]
    for path in DARK_ASSETS + LIGHT_ASSETS + ramp_paths:
        full = os.path.join(ROOT, path)
        if not os.path.exists(full):
            if path.startswith(OPTIONAL_DIRS):
                report.append(f"{path}: not present in this checkout (CI-generated) — skipped")
            else:
                failures.append(f"{path}: missing (expected generated asset)")
    for path, palette in ((p, DARK) for p in DARK_ASSETS):
        if os.path.exists(os.path.join(ROOT, path)):
            name = path
            check_banned(name, read(name), failures, None)
            check_asset(name, palette | TRAFFIC_LIGHTS | (DIVIDER_DARK if "divider" in name else set()),
                        failures, report)
    for path, palette in ((p, LIGHT) for p in LIGHT_ASSETS):
        if os.path.exists(os.path.join(ROOT, path)):
            name = path
            check_banned(name, read(name), failures, None)
            check_asset(name, palette | TRAFFIC_LIGHTS | (DIVIDER_LIGHT if "divider" in name else set()),
                        failures, report)
    for theme, (path, stops) in RAMP_ASSETS.items():
        if os.path.exists(os.path.join(ROOT, path)):
            check_banned(path, read(path), failures, None)
            check_ramp(path, theme, stops, failures, report)

    params = check_readme_params(failures)

    print("palette smoke test")
    for line in report:
        print("  ok  " + line)
    print(f"  ok  README.md: {params} badge colour parameters checked")
    if failures:
        print(f"\nFAIL — {len(failures)} off-palette finding(s):")
        for line in failures:
            print("  x   " + line)
        return 1
    print("\nPASS — every scanned asset is on the Phase 1 palette.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
